### ISSUE TITLE
[BUG] - input filename collision

### ISSUE THREAD

**Issue by erinyoung** [CDCgov/phoenix#100]
**Describe the bug**
I don't know if you want to do anything about this, but right now there's no check in the sample sheet to see if two samples are named the same thing. 

This is a user-generated error caused by the end user, which was me.

**Impact**
Fails at multiqc step.

**To Reproduce**
Have two samples named the same thing

**Expected behavior**
It failed at the last step, I don't know if you want it to fail before the workflow starts.

**Screenshots**
```
Workflow execution completed unsuccessfully
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:MULTIQC'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:MULTIQC` input file name collision -- There are multiple input files for each of the following file names: 1326569_2_fastqc.zip, 1326569_1_fastqc.zip


Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Logs**

**Additional context**
I still think this is a user error, but I thought I would let you know.

**Comment by jvhagey** [comment]
Thanks for reporting this, probably best to address it so resources aren't wasted due to typos. Added a check for duplicate sample id and fastq files in [commit fd6127f](https://github.com/CDCgov/phoenix/commit/fd6127ff091d0e455a7d553415f3a5229ab6b2ec). Change will be in next release (v1.2.0).
