### ISSUE TITLE
MLST_Check_error

### ISSUE THREAD

**Issue by fnindo** [CDCgov/phoenix#106]
I ran into this error at MLST check step for one of the samples, and I am  not sure if there is fix for this:
[phoenix.log](https://github.com/CDCgov/phoenix/files/11385037/phoenix.log)

**Comment by jvhagey** [comment]
Hi @fnindo thanks for reporting this. Can you fill out the rest the the issue template. i.e. please provide the command you used to run PHoeNIx and the system time you are working on.

**Comment by fnindo** [comment]
Hi @jvhagey I ran phoenix using this command:
nextflow run $phoenix_path -profile singularity -entry PHOENIX --input $manifest --kraken2db $kraken2db --outdir $outdir/phoenix --max_cpus $threads --max_memory $memory

**Comment by fnindo** [comment]
I just ran it today

**Comment by fnindo** [comment]
Hi Jill,
It appears that the error was associated with Pubmlst.org Acinobacter baumanii  db being down as my colleague Jared was able to run that sample successfully this morning.

**Comment by jvhagey** [comment]
oh good, because just retrying it was going to be my suggestion. We are working on adding in some handling for when pubMLST goes does as it seems to happen with some regularity.
