### ISSUE TITLE
Issue with running Phoenix on Terra

### ISSUE THREAD

**Issue by lindseyb1234** [CDCgov/phoenix#114]
My workflows for Phoenix on Terra keep failing and am not sure what I am doing wrong. I redownloaded the new kraken database since originally, I had characters Terra didn't like. After that, I resubmitted and the workflow continued and then it failed. Any help to try to fix what I am doing would be greatly appreciated!! :) 
[Phoenix.log 230726.docx](https://github.com/CDCgov/phoenix/files/12184515/Phoenix.log.230726.docx)

**Comment by jvhagey** [comment]
Hi @lindseyb1234,

Looks like your database is named `k2_eupathdb48_20230407.tar.gz` the `eupath` portion of this name means you used the Eukaryotic pathogen genomes kraken database and it doesn't have the files that PHX is expecting. This database also won't work as we need a Bacterial genome database.  Use the Standard-8 version of the kraken database:
![image](https://github.com/CDCgov/phoenix/assets/21023514/91faa236-39cd-4ffb-92c4-1fd201dc708e)

Here is the link to use: https://genome-idx.s3.amazonaws.com/kraken/k2_standard_08gb_20230605.tar.gz

**Comment by lindseyb1234** [comment]
Thank you so much for your help!! I am glad it was a simple fix! I redownloaded the correct database and it finally went through and was successful. Thank you so so much again for all your help!!

**Comment by jvhagey** [comment]
Glad you got it going! Also, be aware that next week there will be a new release v2.0.2 to address a bug with MLST we found. No changes to how you run it though so just follow the steps you just did and it should be good.
