### ISSUE TITLE
MLST db error

### ISSUE THREAD

**Issue by AmyR05** [CDCgov/phoenix#115]
**Describe the bug**
Error received during the PHOENIX:PHOENIX_EXTERNAL:DO_MLST:MLST process:

**Impact**
Cannot complete pipeline

**To Reproduce**
- HPC environment/singularity
- v2.0.1
-nextflow run cdcgov/phoenix -r v2.0.1 -entry PHOENIX -profile singularity,unlhcc --input   /lustre/work/nphl/amyrod/CRE/AR230147/HAISAMPLESHEET.csv --kraken2db /work/HCC/BCRF/app_specific/phoenix-minikraken2db/06052023/ --outdir $PWD/Results
- Custom config:  process {
            executor   = 'slurm' 
            cpus = 2
    memory = '10 GB'
    time = '1 hour'
    queueSize = 10
    submitRateLimit = '10 min'
    queue = 'batch'
- container creation failed: mount hook function failure: mount /$PATH/new_DBS_20230502/20230504/MLST/db->/mlst-2.23.0/db error: while mounting /$PATH/new_DBS_20230502/20230504/MLST/db: mount source /$PATH/new_DBS_20230502/20230504/MLST/db doesn't exist
- Include the files that caused the error  
  - (if the file(s) contains something you don't want public open an issue with a brief description AND then email HAISeq@cdc.gov with the title QH ISSUE # so we can track the problem. DO NOT send PII!

[execution_trace_2023-07-27_14-06-58.txt](https://github.com/CDCgov/phoenix/files/12187674/execution_trace_2023-07-27_14-06-58.txt)

**Comment by jvhagey** [comment]
Hi @AmyR05, unfortunately you have discovered a VERY bad 🐛 . A path was hard coded that shouldn't be (YIKES). So this is a "its not you, its us" situation. We realized this yesterday and have been working on a fix. There will be a v2.0.2 release to address this and are trying to get something sorted ASAP. Until its resolved please continue using the older version. 

Are you using Docker or Singularity?

Thanks for reporting this and I appreciate the patience as we work on a fix.

**Comment by mollymitchell70** [comment]
Hi Jill, we are also seeing this error within the SE BRR region - just leaving this comment here so I get a notification if updates on a fix come through! Thanks for your help :)

**Comment by jvhagey** [comment]
A new release [#116 ](https://github.com/CDCgov/phoenix/releases/tag/v2.0.2) has been created to address this. Let me know if this resolves the issue.

**Comment by AmyR05** [comment]
I have completed this updated version of Phoenix with no further issues.  Thank you Jill!
