### ISSUE TITLE
NCBI_Assembly_stats_20230504.txt clarification

### ISSUE THREAD

**Issue by cimendes** [CDCgov/phoenix#119]
Greetings!!

I've been researching how the median and std are calculated by phoenix when outputting the assembly ratio assessment. I came across the NCBI_Assembly_stats_20230504.txt that is used by https://github.com/CDCgov/phoenix/blob/main/bin/calculate_assembly_ratio.sh but I'm having a hard time understanding what the columns of this file mean, and how it was obtained.

Could you please clarify? 

Thank you!
Inês

**Comment by jvhagey** [comment]
@cimendes please see [wiki documentation](https://github.com/CDCgov/phoenix/wiki/Pipeline-Overview#qc-of-assembled-scaffolds--500bps). I just added information on the headers. Are you just curious or is there an issue related to this?

**Comment by cimendes** [comment]
Just curious! Is it possible to share the script used to compute those statistics? :)

**Comment by jvhagey** [comment]
Unfortunately, we are not able to provided additional scripts. Thanks for the question.
