### ISSUE TITLE
Memory issue when running test install script

### ISSUE THREAD

**Issue by bdelavan** [CDCgov/phoenix#121]
**Describe the bug**
A clear and concise description of what feature is not working.

Good afternoon. I am running the test script from the github page. I am getting the following error:

**Impact**
Unable to complete test install of PHoenix

**To Reproduce**
I am working on a local machine. Phoenix version 2.0.0

**Expected behavior**
Complete test script

**Screenshots**
![image](https://github.com/CDCgov/phoenix/assets/91744154/cb97e92d-19a6-4ef9-9e44-92ed91f1c09c)

**Comment by jvhagey** [comment]
Hi @bdelavan can you provide some information on what group you are with and the specs of the machine you are using? This isn't a bug, there are min memory requirements and your machine does not have enough memory as the error states. I would try passing `--max_memory 10GB`

Alternatively, you could go into the conf file and reduce the memory for the BBDuk steps [here](https://github.com/CDCgov/phoenix/blob/e4dd6018420f315285106e970de2a3103eb1e253/conf/base.config#L72 ) and [here](https://github.com/CDCgov/phoenix/blob/e4dd6018420f315285106e970de2a3103eb1e253/conf/base.config#L78) to 6GB and see if it runs. The [SPAdes ](https://github.com/CDCgov/phoenix/blob/e4dd6018420f315285106e970de2a3103eb1e253/conf/base.config#L90) and [PROKKA ](https://github.com/CDCgov/phoenix/blob/e4dd6018420f315285106e970de2a3103eb1e253/conf/base.config#L102) steps are the other steps that will be a bit of a memory hogs and I am unsure if it will finish with less memory.

Keep in mind that even if the Test profile runs to completion actually isolate files will require more memory as the test sample is a pretty small sample that is just meant to test the system. Let me know it goes and thanks for trying PHoeNIx! Lastly, I would use the 2.0.2 version as the last number is lets you know there was a patch to deal with bugs :)

**Comment by bdelavan** [comment]
Thank you for the quick response!

I am with the Arkansas Department of Health.

Here are the specs:

***@***.***

**Comment by bdelavan** [comment]
I can get more RAM installed. We are really wanting to use the PHOENIX program.

**Comment by bdelavan** [comment]
Issue resolved...need more memory on my end

**Comment by bdelavan** [comment]
Thank you for the quick response!

**Comment by jvhagey** [comment]
This [discussion has details](https://github.com/CDCgov/phoenix/discussions/110) of Laptops have worked to run PHoeNIx. We might have to work on making a custom config file as well.
