### ISSUE TITLE
Workflow execution completed unsuccessfully. Exit status 125

### ISSUE THREAD

**Issue by Murujit** [CDCgov/phoenix#126]
Hello 
 My analysis always stopped at the MLST part. 
I can't find the yml file to fix the flag as suggested...
How to fix this error ( is it a docker/mlst or a scripts problem ?  )

see the report 
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 125.

The full error message was:

Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:DO_MLST:MLST (Klebsiella_pneumoniae)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:DO_MLST:MLST (Klebsiella_pneumoniae)` terminated with an error exit status (125)
Command executed:
# Add in generic header
  sed -i '1i source_file  Database  ST  locus_1 locus_2 locus_3 locus_4 locus_5 locus_6 locus_7 locus_8 lous_9  locus_10' Klebsiella_pneumoniae.tsv
  
  #getting database version)
  mlst_db_version=$(cat ./db/db_version)
  
  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:DO_MLST:MLST":
      mlst: $( echo $(mlst --version 2>&1) | sed 's/mlst //' )
      mlst_db: $( cat db/db_version | date -f - +%Y-%m-%d )
  END_VERSIONS

Command exit status:
  125

Command output:
  (empty)

Command error:
  unknown shorthand flag: 'B' in -B
  See 'docker run --help'.
Work dir:
  /mnt/<path>/E_32_PhoeNIx/work/d1/008a2c5d66691877875f93084a31f5
Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Thanks

**Comment by jvhagey** [comment]
Hi @Murujit, can you provide some the following information:
1. the command used to run phx
2. version of phx you are using
3. why kinda of system you are running this on (i.e. laptop, HPC, cloud etc).

**Comment by jvhagey** [comment]
This is a bug as "-B" is for singularity not docker. This bug was in v2.0.0 and v2.0.1. It has been resolved in the latest version v2.0.2. so please switch to the newest version to resolve this issue. Let me know if there are further problems after this.

**Comment by Murujit** [comment]
Yes, that solved the problem.
Thank you
