### ISSUE TITLE
Griphin steps being failed while running

### ISSUE THREAD

**Issue by shovanmoon** [CDCgov/phoenix#127]
-[cdcgov/phoenix] Pipeline completed with errors-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:GRIPHIN (1)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:GRIPHIN (1)` terminated with an error exit status (1)

Command executed:

  full_path=$(readlink -f results)
  
  GRiPHin.py -d $full_path -a ResGANNCBI_20230517_srst2.fasta --output results --coverage 30 --phoenix 
  
  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:GRIPHIN":
     python: $(python --version | sed 's/Python //g')
     phoenix_base_container: base_v2.0.2
  END_VERSIONS

can any one help me to solve the issue?
I used to run the pipeline successfully. However, after editing some ram value this error is appearing everytime I run the pipeline.

**Comment by jvhagey** [comment]
What ram value did you edit? How are you running this (HPC, laptop, cloud etc)?

**Comment by shovanmoon** [comment]
Thanks for your valuable suggestions regarding ram and the cdcde.config. 

yeah I have run this sample succesfully two times before geting this error. 

I have attached rest of the command, also the NG_S32_trimmed_read_counts.txt files and the summaryline.tsv
![Screenshot from 2023-11-14 15-01-03](https://github.com/CDCgov/phoenix/assets/153198560/424a928a-8d4b-47f0-a378-0cc1fe258cec)
![Screenshot from 2023-11-14 15-01-46](https://github.com/CDCgov/phoenix/assets/153198560/a8e0effd-562a-4a5f-b6bf-46720c2f20c9)
![Screenshot from 2023-11-29 23-41-09](https://github.com/CDCgov/phoenix/assets/153198560/43b02535-d06c-4b02-ba37-8a047b7f8018)

I have matched the trimmed_read_count.txt files with the suceesful one, it seems okay to me.

**Comment by jvhagey** [comment]
So the error is "Not a directory". There seems to be a lock on the file that is preventing it from opening the file for some reason. I would try deleting that folder and rerunning with output to a different directory. Perhaps the pipeline died halfway through in that directory and it didn't unlock the file and then rerunning hit the error. 

Two other things:
1.  Are you with a state public health lab? If so there might be a more suitable pipeline to run for Gonorrhoaeae if you email HAISeq@cdc.gov we can connect you. 
2.  Crop the bottom on the image off so you don't show your computer name :)

**Comment by shovanmoon** [comment]
Great Jvhagey.... 

Thanks you a lot. After reading your last comment, I deleted all the previous files. and run the sample again and its completed succesfully. Thanks a lot for being with me. 
 I work in a genomic lab in icddrb bangladesh. Working with CDC funded ARCH project where  mostly deal with AMR organisms. One of the bioinformatican from CDC helped us to run this pipeline for the project samples. Currently installing this pipeline to run COlre organisms  from this project. And, this sample just a test sample to test if the pipeline working well.
However, can I use any other suitable pipeline for COlre bacteria? Then How should I connect? 

Beside setting this pipeline I am also trying to installing it in my offical desktop. But in that case the test run failed in halfway always. Can you help me solving the issue while i m working with officie desktop?

Sure editing those picture with my laptop name :)

**Comment by jvhagey** [comment]
ok, as the install is a separate issue I am going to close this issue. Kara will reach out to you about appropriate pipelines and if the install remains a problem open a new issue for it. Thanks for using PHX and being part of ARCH :)
