### ISSUE TITLE
[New Feature Request] - Why don't fastp, quast, and potentially other tools make it to the multiqc report?

### ISSUE THREAD

**Issue by jfnjdoh** [CDCgov/phoenix#128]
When running the test sample or my own samples, reports from tool like fastp, QUAST, and potentially others, don't make it into the multiqc report. Both [fastp](https://multiqc.info/modules/fastp/) and [QUAST](https://multiqc.info/modules/quast/) are supported by multiqc and the files that it uses (fastp json and QUAST report.tsv) exist. Could this be an issue of which directory multiqc is run on or when the multiqc process is called in the nextflow workflow?

**Comment by jvhagey** [comment]
Hi @jfnjdoh, this isn't a bug we didn't configure to do this yet. I think it would be helpful for users review so we will work to add this in v2.2.0 as v2.1.0 should be out by the end of the month and I don't want it delayed for this. Thanks for your suggestion, I will leave the issue open until fixed.

**Comment by jvhagey** [comment]
Fixed with [commit ](https://github.com/CDCgov/phoenix/commit/eaaf46cb1089c7a39fdb2d19e77e9a45c024f925). Will be out in the next release of phx. Please reopen if it is not as expected.
