### ISSUE TITLE
SPAdes_Failure that points to empty single reads file in v2.0.2

### ISSUE THREAD

**Issue by TK-DPH** [CDCgov/phoenix#132]
PHoeNIx version: v2.0.2
Nextflow: 23.04.4
HPC: HiPerGator

PHoeNIx failed 4 isolates due to Auto_QC_Failure_Reason: SPAdes_Failure from each *_summaryline_failure.tsv. Impact of this SPAdes Failure is that most results in the summary files are "Unknown". SPAdes failed due to an empty single reads file "{sample}.singles.fastq.gz" which was supposed to be produced by FastP trimming.

From the nextflow log there is a line for each sample:
"error [nextflow.exception.ProcessFailedException]: Process `PHOENIX:PHOENIX_EXTERNAL:SPADES_WF:SPADES ({sample})` terminated with an error exit status (255)"

From the spades_wf work directory, each {sample}.synopsis file shows: "ASSEMBLY: FAILED: {sample}.scaffolds.fa.gz not found"

The .command.log files show: "== Error ==  file is empty: path/{sample}.singles.fastq.gz (single reads, library number: 1, library type: paired-end)"

From the documentation, ".singles.fastq.gz" files are output from fastp_trimd, so I checked that step next in the .nextflow.log (attached below). The TaskProcessor from DEBUG lines all show "Skipping output binding because one or more optional files are missing: fileoutparam<6:1>"

I am trying to find out what went wrong in the FASTP_TRIMD step. From that step, the .command.out is empty and .command.err doesn't say much, so  attached is the .command.sh from one isolate out of four.

Attached logs:
[nextflow.log](https://github.com/CDCgov/phoenix/files/14226427/nextflow.log)
[fastp_trimd-command.sh.txt](https://github.com/CDCgov/phoenix/files/14226539/fastp_trimd-command.sh.txt)

**Comment by jvhagey** [comment]
Hi @TK-DPH can you check that this is still an issue with the newest v2.1.0 version? If so we will continue with troubleshooting.

**Comment by jvhagey** [comment]
What is the sample name and the full file name? I think this is related to #142 we are working on a patch

**Comment by TK-DPH** [comment]
File names look like "2021LY00045_1.fastq.gz" and "2021LY00045_2.fastq.gz" for example, and sample name "2021LY00045" . If I go into the phx_output directory for that one in "phx_output/2021LY00045/file_integrity/2021LY00045_summary.txt" it only states the following: PASSED: File 2021LY00045_ is not corrupt.
PASSED: File 2021LY00045_ is not corrupt.

**Comment by jvhagey** [comment]
@TK-DPH, I also see there is a comment "None of paired reads aligned properly" in the spades.log, which is probably why its not making scaffolds. Again it would be good to confirm that your local copy isn't different from NCBI.  Let me know so we can move forward with a patch release and close this issue.
