### ISSUE TITLE
Phoenix 2.1.0 MultiQC 

### ISSUE THREAD

**Issue by AmyR05** [CDCgov/phoenix#142]
While running Phoenix 2.1.0 "Pipeline completed successfully" message appears and pipeline terminates with no errors, however not all processes are actually ran and final results/reports are not available.

- HPC
- Phoenix v2.1.0
- command $ nextflow run cdcgov/phoenix -r v2.1.0 -entry PHOENIX -profile singularity,unlhcc --input /lustre/work/nphl/amyrod/CRE/AR240052/HAISAMPLESHEET.csv --kraken2db $PHOENIXv2_KRAKEN2/ --outdir $PWD/Results --create_ncbi_sheet

- Appears as if pipeline is terminated after multiqc. However, this happens with multiple samples that were previously analyzed with Phoenix v2.0.2 and had passed.

[execution_trace_2024-02-13_11-50-23.txt](https://github.com/CDCgov/phoenix/files/14271297/execution_trace_2024-02-13_11-50-23.txt)
[.nextflow.log.log](https://github.com/CDCgov/phoenix/files/14271298/default.nextflow.log.log)
![PHX 2 0 2 Not completing processes](https://github.com/CDCgov/phoenix/assets/140753621/8f2bc7c0-048f-44dc-b56c-63a0115d728e)
[unlhcc.config.txt](https://github.com/CDCgov/phoenix/files/14271314/unlhcc.config.txt)

**Comment by jvhagey** [comment]
Hi @AmyR05, it looks like the GRiPHin step finished is there not a GRiPHin file produced? If so can you provide it? This sample is failing the corruption check we added with this version of phoenix, so something is up with those files either file integrity wise or some other bug. What is the extension on these files? Does it happen to be `.fq.gz`?

**Comment by AmyR05** [comment]
Good morning,

The GriPHin summary generated is attached. I have also attached the file_integrity summary generated from the pipeline. Our inputs are .fastq.gz, which is what we have used for the previous versions of Phoenix.

Thanks!
Amy

**Comment by jvhagey** [comment]
Hi @AmyR05, you need to attach the files to the github discussion. They don't show up if you send them in back via email.

**Comment by AmyR05** [comment]
[AR240052_summary.txt](https://github.com/CDCgov/phoenix/files/14347995/AR240052_summary.txt)
[Results_GRiPHin_Summary.xlsx](https://github.com/CDCgov/phoenix/files/14347998/Results_GRiPHin_Summary.xlsx)

**Comment by jvhagey** [comment]
Hey, @AmyR05 I just realized that the`.nextflow.log` you sent is for a different sample and is the older `v2.0.2` of phx. Can you send the one for the failed sample? Also, are these AR Bank samples? I want to run it on my side to see what is going on. If the raw sequences aren't public you can email HAISeq@cdc.gov for me to get access to.

**Comment by AmyR05** [comment]
[v2.1.0.nextflow.log](https://github.com/CDCgov/phoenix/files/14375300/v2.1.0.nextflow.log)
This should be the correct log. This is an AR Bank sample, however it was not loaded to NCBI per ARLRN guidelines as it is KPC+. My colleague will email the fastq files to the designated email for troubleshooting.  I had this same issue with all samples I have attempted on this version of Phoenix though.

**Comment by jvhagey** [comment]
ok, this is a file name parsing issue. Things got messed up as there was multiple instance of "R2" in the full file name, which is usually what we use for telling reverse from forward reads. I have a fix and will get a patch sorted out in the next week. Thanks for bringing this to our attention.
