### ISSUE TITLE
[BUG] - AMRFinder failing with core dump error on Terra

### ISSUE THREAD

**Issue by cimendes** [CDCgov/phoenix#143]
**Describe the bug**

When running on **Terra**, version v2.1.0 and v2.0.2, the workflow isn't successful, failing with the following error message:

```
*** ERROR ***
'/opt/conda/envs/amrfinderplus/bin/blastn' -query '2024CW-00002.filtered.scaffolds.fa' -db /cromwell_root/tmp.5ad5e589/amrfinder.GROWyp/db/AMR_DNA-Klebsiella_oxytoca -evalue 1e-20 -dust no -max_target_seqs 10000 -num_threads 2 -mt_mode 1 -outfmt '6 qseqid sseqid qstart qend qlen sstart send slen qseq sseq' -out /cromwell_root/tmp.5ad5e589/amrfinder.GROWyp/blastn > /cromwell_root/tmp.5ad5e589/amrfinder.GROWyp/log 2> /cromwell_root/tmp.5ad5e589/amrfinder.GROWyp/blastn-err
status = 34304
terminate called after throwing an instance of 'ncbi::CCoreException'
terminate called recursively
Aborted (core dumped)
```

The workflow was run with default parameters, which correspond to 8 CPUs and 64 GB of RAM.
I've tried running again by increasing the RAM provided (128 GB) but the error persisted (I didn't change the CPU as it seems to be set to 2 regardless of the number of CPUs provided)  

Do you have any insight on what could be the cause of this error? 
Thank you!

**Comment by jvhagey** [comment]
Hey @cimendes, I haven't seen this before. Is it sample specific? Are there any public files (raw fastqs) that I can use to recreate this?

**Comment by michellescribner** [comment]
Hi @jvhagey! Yes, this was a sample specific issue and unfortunately not yet submitted to a public repository. It will be submitted after other QC metrics can be assessed. We'll try to provide a few more details shortly!

**Comment by cimendes** [comment]
Hello @jvhagey! After increasing the resources provided to phoenix the workflow finished successfully. 
I'm closing this issue as phoenix was innocent in this failure 😄 

Thank you for the assistance!

**Comment by michellescribner** [comment]
@jvhagey, Ines increased the 'memory' parameter in the Phoenix workflow (v2.1.0) on Terra to `128` which resulted in successful workflow completion. This is not a common issue to our knowledge so may not require a change to default resource settings. The reads have now been submitted to NCBI with accession SRR28055183 if you'd like to try for yourself! Thanks again!
