### ISSUE TITLE
Update ICA, Terra handling to remove launchdir from module

### ISSUE THREAD

**Issue by slsevilla** [CDCgov/phoenix#149]
# Description
Currently the ICA handling of scripts is written as variables with the launchDir being called directly in the module. This is affecting the ability for the output of these modules to cache correctly (relating to #129).

Also adding Terra to this type of refactoring

# Solution
- Rewrite module as a `def`
- Create param for path so that launchDir is only called in the config

**Comment by jvhagey** [comment]
addressed with https://github.com/CDCgov/phoenix/commit/a17b58fe9d750d42c06afbaa34bdf4c6a1a9ac7f  will be in v2.2.0 when its released.
