### ISSUE TITLE
handle flags in nextflow.config rather than in main/modules

### ISSUE THREAD

**Issue by slsevilla** [CDCgov/phoenix#150]
# Description
- move flags from within main.nf / phoneix.nf to config to improve reproducibility and documentation

**Comment by slsevilla** [comment]
- create busco with commit 320cb64f1e824d5a7672fc513e13935af3ec9075

**Comment by jvhagey** [comment]
If people want to run BUSCO they can just use the entry CDC_PHOENIX. Not sure what the utility of adding additional flags would be, I am trying to keep this not complicated for non-power users. Reopen if there is more interest in this.
