### ISSUE TITLE
[BUG] - Undocumented setting docker.userEmulation

### ISSUE THREAD

**Issue by jfnjdoh** [CDCgov/phoenix#169]
Using: 
Docker version 26.1.3, build b72abbb
Ubuntu 22.04.4 LTS
nextflow version 24.04.2.5914

and running 
`nextflow run phoenix/main.nf -profile test,docker -r v2.1.1 -entry PHOENIX --kraken2db ${KDB}` 
where `${KDB}` is  a valid path, I receive the error 

```
WARN: Undocumented setting `docker.userEmulation` is not supported any more - please remove it from your config
ERROR ~ Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:ASSET_CHECK (1)'
```

Perhaps this is related to https://github.com/nextflow-io/nextflow/pull/4596

**Comment by jfnjdoh** [comment]
Software versions are the first few lines of the original post. It kills the whole pipeline, failing at the `PHOENIX:PHOENIX_EXTERNAL:ASSET_CHECK`  Here's a .nextflow.log file
[log.txt](https://github.com/CDCgov/phoenix/files/15485984/log.txt)

**Comment by slsevilla** [comment]
I ran into the same issue - it's related to nextflow 24.04. I rolled back to 23.10 and the pipeline went on without an issue.

There's a few schema / semantic / variables no longer being used that will eventually have to be addressed, but that'll be a pretty big lift.

**Comment by slsevilla** [comment]
Yeah it's not going to work on between 24. There were significant changes made. 

Where are you doing the work? Personal computer? If so you'll need to uninstall the version you have and install nextflow version 23.X, where x is any number. I know that 23.10 works, but I can't speak to other versions.

**Comment by jtsteyer93** [comment]
Yeah, it's a personal computer. at work. I did find a workaround to force the nextflow to be an older version, even if the downloaded version is the most current. This new block is while running v23.10. Thanks for the info for the 23.10 though, I was having such a hard time figuring it out yesterday before finding this thread this morning.

**Comment by jfnjdoh** [comment]
Turns out the simplest, albeit temporary fix is to to simply prepend a nextflow command with `NXF_VER=23.10.1` like so
```
NXF_VER=23.10.1 nextflow run phoenix/main.nf -profile test,docker -r v2.1.1 -entry PHOENIX --kraken2db ${KDB}
```

**Comment by jvhagey** [comment]
ok,  @jfnjdoh  can you try replace [L115](https://github.com/CDCgov/phoenix/blob/717d19c19338373fc0f89eba30757fe5cfb3e18a/nextflow.config#L115) with `docker.runOptions       = '-u $(id -u):$(id -g)'` to the `nextflow.config` and then rerun? Looks like a permissions issue.

**Comment by jfnjdoh** [comment]
Yeah, that solved it. Thanks @jvhagey
