### ISSUE TITLE
[BUG] - create_samplesheet.sh file is no longer available

### ISSUE THREAD

**Issue by snallani-msdh** [CDCgov/phoenix#170]
**Describe the bug**
The "create_samplesheet.sh" file that was previously found in the bin folder is no longer present. 

**Impact**
We were using this file to automate samplesheet creation and now cannot. Not sure if this is an intended change when the latest update was made so I wanted to bring it to your attention.

**Comment by jvhagey** [comment]
Whoops, I think it was removed as it wasn't actively being used in the larger pipeline. I can add it back in the next version. However, you can make a [copy of this](https://github.com/CDCgov/phoenix/blob/v2.0.0/bin/create_samplesheet.sh) to keep on your system. Let me know if that works for you.

**Comment by jvhagey** [comment]
Closing for issue clean up for the new year. Will be addressed with release of new v2.2.0 in 2025.
