### ISSUE TITLE
Blank qc_outcome column

### ISSUE THREAD

**Issue by bajwamoneeb** [CDCgov/phoenix#174]
I used Phoenix on Terra and I got some samples as having a blank for qc_outcome and I am not sure what that signifies or why that is; is it passing or failing? They look to be good quality based on other metrics and pipelines we ran them thru.

**Comment by jvhagey** [comment]
So it looks like both samples had a failure during the second to last step MultiQC that is specific to that program. 

![image](https://github.com/user-attachments/assets/cf8e192f-c223-4e8b-9e5f-d240b8d7826e)

When I back track a bit it looks like something odd is happening with the kraken file:
![image](https://github.com/user-attachments/assets/71a7ec90-0063-4bfa-99b7-b6f3086dae32)

To debug this further I will need to run the samples on my side to get the intermediate files as Terra doesn't copy them if there is a failure. I will send you an email to set up a sharefile folder.

**Comment by jvhagey** [comment]
Closing for issue clean up for the new year. For documentation purposes, this was fixed upgrading MultiQC’s version to `quay.io/biocontainers/multiqc:1.24.1--pyhdfd78af_0` . Will be addressed with release of new v2.2.0 in 2025.
