### ISSUE TITLE
Failed at the "SPADES (Test_Sample)" step

### ISSUE THREAD

**Issue by tkiryuti** [CDCgov/phoenix#47]
Ran step 6 from Quick Start to test PHoeNIx on a test sample and failed at the "SPADES (Test_Sample)". The error message does not specify error (also see log.txt of terminal output, and nextflow.log attached):

[6b/f2ff4e] NOTE: Process `PHOENIX:PHOENIX_EXTERNAL:SPADES_WF:SPADES (Test_Sample)` terminated with an error exit status (1) -- Error is ignored

Ran on University of Florida supercomputer with the following commands:

$ module load nextflow/22.04.5
$ conda activate PHoeNIx
$ singularity version
3.8.6
$ PATH_TO_DB="/home/$PATH/DB/Minikraken2DB"
$ time nextflow run cdcgov/phoenix -r v1.0.0 -profile test,singularity -entry PHOENIX --kraken2db $PATH_TO_DB

### **Logs**
[log.txt](https://github.com/CDCgov/phoenix/files/9854848/log.txt)
[.nextflow.log](https://github.com/CDCgov/phoenix/files/9854847/default.nextflow.log)
[.spades.log_spades_outcome.csv](https://github.com/CDCgov/phoenix/files/9854999/default.spades.log_spades_outcome.csv)

### Relevant .command.err file 
shows it couldn't reach the Test_Sample directory. I double checked this path and it does exist, so **maybe there is an issue with the Singularity bind mount for Spades.**
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (73) bind mounts
cp: cannot create regular file '/blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results/Test_Sample/': No such file or directory
cp: cannot create regular file '/blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results/Test_Sample': No such file or directory
INFO:    Cleaning up image...

### Relevant .command.log file
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (73) bind mounts
Option -k triggered, argument = Test_Sample.trimd_summary.txt
Option -n triggered, argument = Test_Sample
Option -d triggered, argument = /blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results
cp: cannot create regular file '/blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results/Test_Sample/': No such file or directory
cp: cannot create regular file '/blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results/Test_Sample': No such file or directory
INFO:    Cleaning up image...
find: ‘*.spades.log’: No such file or directory

**Comment by erinyoung** [comment]
I ran into this issue as well. This is due to the process looking in the workdir for a "$workdir/blue/$PATH_B/tests/PHoeNIx/2022-10-24-14-50/results/Test_Sample/", which doesn't exist.

**Comment by jvhagey** [comment]
Issues was resolved with BRR offline. Changes that will be pushed in the v1.1.0 release should fix this issue. Problem also described in github issue https://github.com/CDCgov/phoenix/issues/82
