### ISSUE TITLE
amrfinder_update: command not found

### ISSUE THREAD

**Issue by Siddra2021** [CDCgov/phoenix#48]
**Describe the bug**
A clear and concise description of what feature is not working.

**Impact**
Please describe the impact this bug is causing.

**To Reproduce**
- What environment you are running the pipeline in (i.e. HPC, local, cloud etc).
 local
- What version of the pipeline you are using
- The command that was run to cause the error 
Ubuntu, nextflow
- If you used a custom config file please provide it
- The text of the error itself - screenshots are great for this!  

WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org/ for more info.
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE (update)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE (update)` terminated with an error exit status (127)

Command executed:

  mkdir amrfinderdb
  amrfinder_update -d amrfinderdb
  tar czvf amrfinderdb.tar.gz -C $(readlink amrfinderdb/latest) ./

  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE":
      amrfinderplus: $(amrfinder --version)
      amrfinderplus_db_version: $(head amrfinderdb/latest/version.txt)
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 3: amrfinder_update: command not found

Work dir:
  /home/siddra/phoenix/work/51/6bf5a48a4a484ead61f0ef61be686d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
- Include the files that caused the error  
  - (if the file(s) contains something you don't want public open an issue with a brief description AND then email HAISeq@cdc.gov with the title QH ISSUE # so we can track the problem. DO NOT send PII!

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem. These would be the `.command.err`, `.command.out`, `.command.sh` and/or the `.nextflow.log` files associated with the run/process that failed. The `.nextflow.log`  file is in directory you ran the pipeline from. The `.command.XXX` files are found in `<directory you ran pipeline from>/work/XX/xxxxxxxxxxxxxx` here the x and X are a random string of letters/numbers associated with the process. As the pipeline runs on CLI you will see the beginning of these strings to the left of the process that is running. 

**Additional context**
Add any other context about the problem here. If you have done any internet sleuthing already please link to any relevant posts on the topic.

**Comment by jvhagey** [comment]
Hi @Siddra2021, thanks for opening the issue its a good first step. However, you need to fill out the "To Reproduce" section at minimum or we will be unable to assist you. After you have filled that out please delete the rest of the template that is not being used. Also, edit the title to provide a general idea of what your error is so that others can reference this issue if they have a similar error. The idea here is that you need to provide enough information for us to be able to reproduce your error. I need to know how you are running the pipeline to assist you. Thanks!
