### ISSUE TITLE
kraken2_best_hit.sh error

### ISSUE THREAD

**Issue by mndoucette** [CDCgov/phoenix#52]
**Describe the bug**
While testing the install for PHoeNIx the pipeline aborts and generates the following error:
![image](https://user-images.githubusercontent.com/117759817/200687894-31253ffc-abe8-4555-b987-4ab9746d0ab2.png)

Test_Sample.kraken2_trimd.report.txt does exist and is referenced appropriately in the work directory.

**Impact**
The pipeline does not run successfully. 

**To Reproduce**
- local linux environment using Nextflow 21.10.3
- phoenix v1.0.0
- nextflow run ~/.nextflow/assets/cdcgov/phoenix/main.nf -entry PHOENIX -profile test,singularity --kraken2db ~/.nextflow/assets/cdcgov/phoenix/assets/databases/

**Expected behavior**
The pipeline runs successfully.

**Comment by jvhagey** [comment]
Hi @mndoucette, just to confirm you downloaded the `hash.k2d` file from the sharefile and copied it into the `~/.nextflow/assets/cdcgov/phoenix/assets/databases`? Can you attach the `.command.run`, `.command.out` and `.command.err` file from the work directory listed in the error (the folder /Phoenix_test/work/1b/6438 etc....)?

**Comment by mndoucette** [comment]
Hi @jvhagey, yes, `hash.k2d` has been downloaded and copied to `~/.nextflow/assets/cdcgov/phoenix/assets/databases`.

[command.out.txt](https://github.com/CDCgov/phoenix/files/9971960/command.out.txt)
[command.err.txt](https://github.com/CDCgov/phoenix/files/9971961/command.err.txt)
[command.run.txt](https://github.com/CDCgov/phoenix/files/9971962/command.run.txt)

**Comment by jvhagey** [comment]
@mndoucette in that folder is there the file `Test_Sample.kraken2_trimd.report.txt` ? If so what is in it? It is saying that file isn't present in which case the problem might be a bit further upstream. That file is made in the `KRAKEN2_TRIMD` step can you send the `.command.sh`, `.command.out` and `.command.err`?

**Comment by mndoucette** [comment]
@jvhagey `Test_Sample.kraken2_trimd.report.txt` is in that folder, I've attached it below along with the command files from the `KRAKEN2_TRIMD` work directory. The database files appear to be the correct sizes as well. 
![image](https://user-images.githubusercontent.com/117759817/201941686-0cc87e5e-a808-44ef-a55c-2fe8a3bb3b18.png)
[Test_Sample.kraken2_trimd.report.txt](https://github.com/CDCgov/phoenix/files/10013399/Test_Sample.kraken2_trimd.report.txt)
[command.sh.txt](https://github.com/CDCgov/phoenix/files/10013400/command.sh.txt)
[command.err.txt](https://github.com/CDCgov/phoenix/files/10013401/command.err.txt)
[command.out.txt](https://github.com/CDCgov/phoenix/files/10013402/command.out.txt)

**Comment by jvhagey** [comment]
Hi, @mndoucette sorry for the long delay. Just wanted to check in and see if this was resolved (if so how)? Or are you stuck at the same spot?

**Comment by jvhagey** [comment]
As this issue is stale and related to an old version I am closing the issue. please reopen if there is still and issue.
