### ISSUE TITLE
amrfinder_update: command not found

### ISSUE THREAD

**Issue by Siddra2021** [CDCgov/phoenix#53]
**Describe the bug**
Pipeline runs with the following error,

WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE (update)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE (update)` terminated with an error exit status (127)

Command executed:

  mkdir amrfinderdb
  amrfinder_update -d amrfinderdb
  tar czvf amrfinderdb.tar.gz -C $(readlink amrfinderdb/latest) ./

  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:AMRFINDERPLUS_UPDATE":
      amrfinderplus: $(amrfinder --version)
      amrfinderplus_db_version: $(head amrfinderdb/latest/version.txt)
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 3: amrfinder_update: command not found

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Impact**
Not passing test after install 

**To Reproduce**
local environment with version 1.0.0.  Command used is nextflow run ~/phoenix/main.nf -profile test, docker -entry PHOENIX --kraken2db ~/phoenix/assets/databases. The error description is above. 

**Expected behavior**
Should run successfully

**Screenshots**
Screenshot is here. 
![Screenshot (8)](https://user-images.githubusercontent.com/78268926/201522924-87484e03-3a47-44c7-a31f-ba4a2564b91f.png)

**Comment by jvhagey** [comment]
Hi @Siddra2021, can you retry and remove the space between `test` and `docker` so it should be `-profile test,docker` NOT `-profile test, docker`. Let me know if that fixes it.

**Comment by Siddra2021** [comment]
Jill,
Thank you for following up. I fixed the space issue and ran it again
however, I have not been able to run it yet.  I  allocated 6.4 GB to the
docker and ended up with an error message attached. I am running it on a
device that has a total memory of 7.5GB. I am thinking to upgrade memory
and then try. What do you suggest?

Currently, I am running a comparison analysis between Phoenix and the
existing pipeline for HAI analysis and hoping to switch to Phoenix. Would
appreciate any feedback.

Siddra

**Comment by jvhagey** [comment]
@Siddra2021 When you say "existing pipeline" does that mean Quaisar or your internal one? In terms of memory, you can check out [this file](https://github.com/CDCgov/phoenix/blob/v1.0.1/conf/base.config) for some more specifics on memory required for each step. For `-entry PHOENIX` the PROKKA step takes the most memory and needs ~45GB depending on the sample. So a machine with a total of 7.5GB isn't going to be able to run the pipeline. 😭

**Comment by Siddra2021** [comment]
Currently, we are comparing Phoenix with CLC genomics. Are there any other
comparisons for Phoenix done? Yes, agree, 7.5 GB is not enough. I am
updating the memory to support the pipeline.

Siddra

**Comment by jvhagey** [comment]
We compared to PHX to the old Quaisar-H pipeline, but really its apples to oranges at this point. I don't know of public comparisons, but I know a lot of other state labs compared it to what they had been using (if they did have something). I did get a [question from Robert](https://github.com/CDCgov/phoenix/issues/51) in WY about some coverage calculation differences (I think compared to his [bactopia ](https://bactopia.github.io/v2.2.0/) pipeline). When the paper on PHoeNIx comes out it will have comparisons, but just aren't at that point yet. Have you been able to get the pipeline running with addtional memory? If so I'll close this issue.

**Comment by Siddra2021** [comment]
Jill,

Thank you for your feedback.  We are currently running Abricate for CRE
analysis and comparing Phoenix results to what we have before we switch to
Phoenix. I am waiting for memory card to be added to the laptop so I can
run the analysis. Will keep you posted.
Siddra

**Comment by Siddra2021** [comment]
Hello Jill,
I hope you had a wonderful break. I have been able to get additional memory
to my laptop and no longer get the memory error. However, I am now getting
another error. Please see the screenshot. I would appreciate any help.

Thank you again,
Siddra

**Comment by jvhagey** [comment]
@Siddra2021 Looks like you are replying via email rather than on github so the screenshot doesn't come through in this way. I'd suggest you reply via github. Since the initial issue is resolved I am going to close this and you will need to open a new one for the new issue. This makes sure that we get all the information we need to address the issue and also helps others easily search the issues to to find help on a similar problem.

**Comment by Siddra2021** [comment]
Ok, Thank you.
Siddra
