### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Siddra2021** [CDCgov/phoenix#85]
**Describe the bug**
Pipeline runs successfully but no output is produced
**Impact**
No output generated

**To Reproduce**
- What environment you are running the pipeline in (local 
- What version of the pipeline you are using 1.0.0
- The command that was run to cause the error 
- nextflow run cdcgov/phoenix -r v1.0.0 -profile docker -entry PHOENIX --input ~/phoenix/samplesheet.csv --kraken2db ~/phoenix/assets/databases/
- If you used a custom config file please provide it
- The text of the error itself - screenshots are great for this!
- Attached  

**Expected behavior**
should run successfully

**Screenshots**
IAttached
![Screenshot (21)](https://user-images.githubusercontent.com/78268926/215634970-bd3797cb-931f-484f-be6f-bf68a04ad80f.png)

**Comment by jvhagey** [comment]
Hi @Siddra2021, can you provide the `.command.out` and `.command.err` files for that spades step? We need to know why spades is failing.

**Comment by Siddra2021** [comment]
[.command.err.txt](https://github.com/CDCgov/phoenix/files/10549464/default.command.err.txt)
[.command.out.txt](https://github.com/CDCgov/phoenix/files/10549465/default.command.out.txt)

**Comment by Siddra2021** [comment]
Please see the attached above.

**Comment by jvhagey** [comment]
@Siddra2021 it seems these are not specific to the SPAdes step, these are for the multiQC step. you need to follow the path to the spades specific step (in your case this is `ef/dcBcc3`).

**Comment by jvhagey** [comment]
@Siddra2021 this is the same issue as #82 please read my responses there.
